# Generated by Django 5.2.8 on 2025-11-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=30, null=True)),
                ('book_status', models.BooleanField(default=False)),
            ],
        ),
    ]
